version: '3.1'

services:
  db:
    image: postgres
    user: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - /Users/teopopescu/Desktop/fastapi-practice/postgresDBSamples/adventureworks/db-files:/var/lib/postgresql/data
    ports:
      - "5432:5432"
